"""unique portfolio name per user

Revision ID: df4f4ee2a2d6
Revises: 892486306834
Create Date: 2026-04-18 15:26:24.823674+10:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4f4ee2a2d6'
down_revision: Union[str, Sequence[str], None] = '892486306834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_portfolio_name', 'portfolios', ['owner_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_portfolio_name', 'portfolios', type_='unique')
    # ### end Alembic commands ###
